version: '3.0'

services:
  app:
    image: docker-img
    build: .
    ports:
      - ${PORT}:${PORT}
    restart: always
    working_dir: /app
    volumes:
      - ./:/app

networks:
  backend-net:
    driver: bridge