version: '3.0'

services:
  postgres:
    container_name: my_database
    image: postgres:14
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    volumes: 
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app-network
  app:
    container_name: my_app
    image: docker-img
    build: .
    ports:
      - ${PORT}:${PORT}
    restart: always
    working_dir: /app
    volumes:
      - ./:/app
      - vol-logs:/logs
    networks:
      - app-network
    command: npm run start:docker
    depends_on:
      - postgres

networks:
  app-network:
    driver: bridge

volumes:
  vol-logs:
  postgres-data: